on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master

jobs:
  build:
    name: BUILD THE CURRENT BRANCH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: |
          # Check if commit message contains [skip build]
          if [[ $(git log -1 --pretty=%B) == *"[skip build]"* ]]; then
            echo "Skipping the build as commit message contains [skip build]."
          else
            npm run build --prod
          fi
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: ./public

  deploy:
    name: DEPLOY TO FIREBASE STOCKMARKET000
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
      - name: Install Dependencies
        run: npm install
      - name: Build the app artifact for prod
        run: npm run build --prod
      - name: Deploy angular app to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PDFFREETOOLS}}'
            channelId: live
            projectId: pdffreetools
        env:
            FIREBASE_CLI_EXPERIMENTS: webframeworks
